### ISSUE TITLE
업무상태 기능

### ISSUE THREAD

**Issue by kimmj13** [douzone3group/prosync_back#7]
## Description
업무상태 기능
- 프로젝트에서 업무 상태를 등록하여 순서(seq)를 통해 보임 여부 체크 가능하도록 로직 변경

## To-do
- [x] 업무상태 생성
- [x] 업무상태 수정
- [x] 업무상태 조회
- [x] 업무상태 삭제
- [x] 프로젝트 업무상태 리스트 조회 (전체조회)
- [x] 프로젝트와 연관 관계 설정 - 프로젝트 생성시 기본 업무상태 (4가지) 추가
- [ ] 프로젝트_회원의 권한 확인하는 로직 --> 강욱님, 동희님
- [x] API (swagger api)

## ETC
구현 예상 기간 : 8/16 ~ 8/18
